name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: System deps for GDAL/rasterio
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev gcc
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff mypy
      - name: Lint
        run: |
          source .venv/bin/activate
          ruff check .
      - name: Type check
        run: |
          source .venv/bin/activate
          mypy app || true
      - name: Unit tests
        run: |
          source .venv/bin/activate
          pytest -q -k "health" --disable-warnings
      - name: Integration smoke (optional)
        continue-on-error: true
        run: |
          source .venv/bin/activate
          pytest -q -k "vector_smoke" -m integration --disable-warnings || true
